spring:
  data:
    mongodb:
      # 아이디, 비밀번호, authSource를 모두 제거한 아주 깔끔한 주소입니다.
      uri: mongodb://localhost:27017/blog3

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB