spring:
  data:
    mongodb:
      uri: mongodb+srv://<계정>:<패스워드>@mongodbtutorial.c24ikv6.mongodb.net/blog3?retryWrites=true&w=majority
      ex) uri: mongodb://localhost:27017/blog3?retryWrites=true&w=majority
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
